REM THIS BATCH SCRIPT REMOVES OLD INSTALLATIONS OF
REM KASPERSKY ENDPOINT SECURITY AND KASPERSKY NETWORK AGENT
REM ON A SINGLE COMPUTER FROM A SHARED FOLDER CONTAINING
REM KASPERSKY INSTALLATION FILES

REM PUSH NETWORK LOCATION OF KASPERSKY
net use \\"SHARED_FOLDER" /user:"DOMAIN\ADMIN_USER" "PASSWORD"
pushd \\"INSTALLATION_FOLDER_OF_KASPERSKY"

REM REMOVE OLD KASPERSKY ENDPOINT SECURITY
10\setup.exe /x /s

REM REMOVE OLD KASPERSKY NETWORK AGENT
cleaner_agent_10.exe /uc {B9518725-0B76-4793-A409-C6794442FB50}
cleaner_agent_10.exe /pc {BCF4CF24-88AB-45E1-A6E6-40C8278A70C5}

REM POP THE PUSHED DIRECTORY
popd

REM REMOVE CONNECTION
net use \\"SHARED_FOLDER" /d
